FROM bcit/alpine:<%= image.labels['alpine_version'] %>
<%= snippet('labels', binding) -%>

ENV RUNUSER nginx
ENV HOME /var/cache/nginx

RUN printf "%s%s%s\n" \
        "https://nginx.org/packages/alpine/v" \
        "<%= image.labels['alpine_version'] %>" \
        "/main" \
    | tee -a /etc/apk/repositories \
 && wget -O /etc/apk/keys/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
 && apk add --no-cache \
    nginx=<%= image.labels['nginx_version'] %>-r<%= image.labels['nginx_apk_release'] %> \
    nginx-module-geoip=<%= image.labels['nginx_version'] %>-r<%= image.labels['nginx_apk_release'] %> \
    nginx-module-image-filter=<%= image.labels['nginx_version'] %>-r<%= image.labels['nginx_apk_release'] %> \
    nginx-module-xslt=<%= image.labels['nginx_version'] %>-r<%= image.labels['nginx_apk_release'] %> \
    nginx-module-njs=<%= image.labels['nginx_version'] %>.<%= image.labels['nginx_njs_version'] %>-r<%= image.labels['nginx_apk_release'] %>

RUN chown nginx:root /var/cache/nginx /var/run /var/log/nginx /run \
 && chmod 770 /var/cache/nginx \
 && chmod 775 /var/run /run /var/log/nginx \
 #required for 50-copy-nginx-config.sh to copy config files
 && chmod 775 -R /etc/nginx/ \
 && ln -sf /dev/stdout /var/log/nginx/access.log \
 && ln -sf /dev/stderr /var/log/nginx/error.log

COPY 50-copy-config.sh /docker-entrypoint.d/
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf

RUN touch /usr/share/nginx/html/ping

USER nginx
WORKDIR /application

EXPOSE 8080
ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
